- name: Configure and deploy DevOps application
  hosts: all
  become: yes

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Python Pip
      apt:
        name: python3-pip
        state: present

    - name: Install Docker SDK for Python
      pip:
        name: docker

    - name: Copy application code
      copy:
        src: /local/path/to/app/
        dest: /opt/devops-app/

    - name: Build Docker image
      command: docker build -t devops-app /opt/devops-app/

    - name: Run Docker container
      command: docker run -d -p 5000:5000 devops-app

